server:
  port: 8888

spring:
  # 配置数据源信息
  datasource:
    url: jdbc:mysql://39.102.133.112:3306/PESYSTEM?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 2413
    driver-class-name: com.mysql.cj.jdbc.Driver

pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  helper-dialect: mysql


swagger:
  enabled: true
  base-package: 'com.hoperun.pesystem.controller'
  title: '会员积分兑换系统接口测试'
  description: '基于Swagger构建的SpringBoot Api 文档'
  version: '1.0'
  contact:
    name: 'PESystem'
    url: ''
    email: 'ljd2413@qq.com'
# 开启 mybatis 驼峰标识
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hoperun.pesystem.mapper


# 日志配置
logging:
  file:
    name: log/PESYSYTEM.log
  level:
    com.hoperun.pesystem.mapper: debug
    root: info
  logback:
    rollingpolicy:
      max-file-size: 200MB
      max-history: 30

beetle:
  # 默认头像链接
  defaultAvatar: https://ljd-website.oss-cn-beijing.aliyuncs.com/defualt.svg
