package com.hoperun.pesystem.model;

import java.io.Serializable;
import java.util.Date;

public class Activity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.a_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Integer aId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.a_title
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private String aTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.a_type
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Integer aType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.a_start_time
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Date aStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.a_end_time
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Date aEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.a_address
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private String aAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.a_photo_index_big_url
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private String aPhotoIndexBigUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.a_photo_index_sm_url
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private String aPhotoIndexSmUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.a_photo_url
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private String aPhotoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.a_introduce
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private String aIntroduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.a_flag
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Integer aFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity.a_information
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private String aInformation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.a_id
     *
     * @return the value of t_activity.a_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.a_id
     *
     * @param aId the value for t_activity.a_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.a_title
     *
     * @return the value of t_activity.a_title
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getaTitle() {
        return aTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.a_title
     *
     * @param aTitle the value for t_activity.a_title
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setaTitle(String aTitle) {
        this.aTitle = aTitle == null ? null : aTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.a_type
     *
     * @return the value of t_activity.a_type
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Integer getaType() {
        return aType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.a_type
     *
     * @param aType the value for t_activity.a_type
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setaType(Integer aType) {
        this.aType = aType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.a_start_time
     *
     * @return the value of t_activity.a_start_time
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Date getaStartTime() {
        return aStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.a_start_time
     *
     * @param aStartTime the value for t_activity.a_start_time
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setaStartTime(Date aStartTime) {
        this.aStartTime = aStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.a_end_time
     *
     * @return the value of t_activity.a_end_time
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Date getaEndTime() {
        return aEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.a_end_time
     *
     * @param aEndTime the value for t_activity.a_end_time
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setaEndTime(Date aEndTime) {
        this.aEndTime = aEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.a_address
     *
     * @return the value of t_activity.a_address
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getaAddress() {
        return aAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.a_address
     *
     * @param aAddress the value for t_activity.a_address
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setaAddress(String aAddress) {
        this.aAddress = aAddress == null ? null : aAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.a_photo_index_big_url
     *
     * @return the value of t_activity.a_photo_index_big_url
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getaPhotoIndexBigUrl() {
        return aPhotoIndexBigUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.a_photo_index_big_url
     *
     * @param aPhotoIndexBigUrl the value for t_activity.a_photo_index_big_url
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setaPhotoIndexBigUrl(String aPhotoIndexBigUrl) {
        this.aPhotoIndexBigUrl = aPhotoIndexBigUrl == null ? null : aPhotoIndexBigUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.a_photo_index_sm_url
     *
     * @return the value of t_activity.a_photo_index_sm_url
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getaPhotoIndexSmUrl() {
        return aPhotoIndexSmUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.a_photo_index_sm_url
     *
     * @param aPhotoIndexSmUrl the value for t_activity.a_photo_index_sm_url
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setaPhotoIndexSmUrl(String aPhotoIndexSmUrl) {
        this.aPhotoIndexSmUrl = aPhotoIndexSmUrl == null ? null : aPhotoIndexSmUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.a_photo_url
     *
     * @return the value of t_activity.a_photo_url
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getaPhotoUrl() {
        return aPhotoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.a_photo_url
     *
     * @param aPhotoUrl the value for t_activity.a_photo_url
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setaPhotoUrl(String aPhotoUrl) {
        this.aPhotoUrl = aPhotoUrl == null ? null : aPhotoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.a_introduce
     *
     * @return the value of t_activity.a_introduce
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getaIntroduce() {
        return aIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.a_introduce
     *
     * @param aIntroduce the value for t_activity.a_introduce
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setaIntroduce(String aIntroduce) {
        this.aIntroduce = aIntroduce == null ? null : aIntroduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.a_flag
     *
     * @return the value of t_activity.a_flag
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Integer getaFlag() {
        return aFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.a_flag
     *
     * @param aFlag the value for t_activity.a_flag
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setaFlag(Integer aFlag) {
        this.aFlag = aFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity.a_information
     *
     * @return the value of t_activity.a_information
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getaInformation() {
        return aInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity.a_information
     *
     * @param aInformation the value for t_activity.a_information
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setaInformation(String aInformation) {
        this.aInformation = aInformation == null ? null : aInformation.trim();
    }
}