package com.hoperun.pesystem.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ActivityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_activity
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    protected String orderByClause;
    protected Integer startNum;
    protected Integer endNum;

    public Integer getStratNum() {
        return startNum;
    }

    public void setStratNum(Integer stratNum) {
        this.startNum = stratNum;
    }

    public Integer getEndNum() {
        return endNum;
    }

    public void setEndNum(Integer endNum) {
        this.endNum = endNum;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_activity
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_activity
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public ActivityExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_activity
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAIdIsNull() {
            addCriterion("a_id is null");
            return (Criteria) this;
        }

        public Criteria andAIdIsNotNull() {
            addCriterion("a_id is not null");
            return (Criteria) this;
        }

        public Criteria andAIdEqualTo(Integer value) {
            addCriterion("a_id =", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdNotEqualTo(Integer value) {
            addCriterion("a_id <>", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdGreaterThan(Integer value) {
            addCriterion("a_id >", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("a_id >=", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdLessThan(Integer value) {
            addCriterion("a_id <", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdLessThanOrEqualTo(Integer value) {
            addCriterion("a_id <=", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdIn(List<Integer> values) {
            addCriterion("a_id in", values, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdNotIn(List<Integer> values) {
            addCriterion("a_id not in", values, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdBetween(Integer value1, Integer value2) {
            addCriterion("a_id between", value1, value2, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdNotBetween(Integer value1, Integer value2) {
            addCriterion("a_id not between", value1, value2, "aId");
            return (Criteria) this;
        }

        public Criteria andATitleIsNull() {
            addCriterion("a_title is null");
            return (Criteria) this;
        }

        public Criteria andATitleIsNotNull() {
            addCriterion("a_title is not null");
            return (Criteria) this;
        }

        public Criteria andATitleEqualTo(String value) {
            addCriterion("a_title =", value, "aTitle");
            return (Criteria) this;
        }

        public Criteria andATitleNotEqualTo(String value) {
            addCriterion("a_title <>", value, "aTitle");
            return (Criteria) this;
        }

        public Criteria andATitleGreaterThan(String value) {
            addCriterion("a_title >", value, "aTitle");
            return (Criteria) this;
        }

        public Criteria andATitleGreaterThanOrEqualTo(String value) {
            addCriterion("a_title >=", value, "aTitle");
            return (Criteria) this;
        }

        public Criteria andATitleLessThan(String value) {
            addCriterion("a_title <", value, "aTitle");
            return (Criteria) this;
        }

        public Criteria andATitleLessThanOrEqualTo(String value) {
            addCriterion("a_title <=", value, "aTitle");
            return (Criteria) this;
        }

        public Criteria andATitleLike(String value) {
            addCriterion("a_title like", value, "aTitle");
            return (Criteria) this;
        }

        public Criteria andATitleNotLike(String value) {
            addCriterion("a_title not like", value, "aTitle");
            return (Criteria) this;
        }

        public Criteria andATitleIn(List<String> values) {
            addCriterion("a_title in", values, "aTitle");
            return (Criteria) this;
        }

        public Criteria andATitleNotIn(List<String> values) {
            addCriterion("a_title not in", values, "aTitle");
            return (Criteria) this;
        }

        public Criteria andATitleBetween(String value1, String value2) {
            addCriterion("a_title between", value1, value2, "aTitle");
            return (Criteria) this;
        }

        public Criteria andATitleNotBetween(String value1, String value2) {
            addCriterion("a_title not between", value1, value2, "aTitle");
            return (Criteria) this;
        }

        public Criteria andATypeIsNull() {
            addCriterion("a_type is null");
            return (Criteria) this;
        }

        public Criteria andATypeIsNotNull() {
            addCriterion("a_type is not null");
            return (Criteria) this;
        }

        public Criteria andATypeEqualTo(Integer value) {
            addCriterion("a_type =", value, "aType");
            return (Criteria) this;
        }

        public Criteria andATypeNotEqualTo(Integer value) {
            addCriterion("a_type <>", value, "aType");
            return (Criteria) this;
        }

        public Criteria andATypeGreaterThan(Integer value) {
            addCriterion("a_type >", value, "aType");
            return (Criteria) this;
        }

        public Criteria andATypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("a_type >=", value, "aType");
            return (Criteria) this;
        }

        public Criteria andATypeLessThan(Integer value) {
            addCriterion("a_type <", value, "aType");
            return (Criteria) this;
        }

        public Criteria andATypeLessThanOrEqualTo(Integer value) {
            addCriterion("a_type <=", value, "aType");
            return (Criteria) this;
        }

        public Criteria andATypeIn(List<Integer> values) {
            addCriterion("a_type in", values, "aType");
            return (Criteria) this;
        }

        public Criteria andATypeNotIn(List<Integer> values) {
            addCriterion("a_type not in", values, "aType");
            return (Criteria) this;
        }

        public Criteria andATypeBetween(Integer value1, Integer value2) {
            addCriterion("a_type between", value1, value2, "aType");
            return (Criteria) this;
        }

        public Criteria andATypeNotBetween(Integer value1, Integer value2) {
            addCriterion("a_type not between", value1, value2, "aType");
            return (Criteria) this;
        }

        public Criteria andAStartTimeIsNull() {
            addCriterion("a_start_time is null");
            return (Criteria) this;
        }

        public Criteria andAStartTimeIsNotNull() {
            addCriterion("a_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andAStartTimeEqualTo(Date value) {
            addCriterion("a_start_time =", value, "aStartTime");
            return (Criteria) this;
        }

        public Criteria andAStartTimeNotEqualTo(Date value) {
            addCriterion("a_start_time <>", value, "aStartTime");
            return (Criteria) this;
        }

        public Criteria andAStartTimeGreaterThan(Date value) {
            addCriterion("a_start_time >", value, "aStartTime");
            return (Criteria) this;
        }

        public Criteria andAStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("a_start_time >=", value, "aStartTime");
            return (Criteria) this;
        }

        public Criteria andAStartTimeLessThan(Date value) {
            addCriterion("a_start_time <", value, "aStartTime");
            return (Criteria) this;
        }

        public Criteria andAStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("a_start_time <=", value, "aStartTime");
            return (Criteria) this;
        }

        public Criteria andAStartTimeIn(List<Date> values) {
            addCriterion("a_start_time in", values, "aStartTime");
            return (Criteria) this;
        }

        public Criteria andAStartTimeNotIn(List<Date> values) {
            addCriterion("a_start_time not in", values, "aStartTime");
            return (Criteria) this;
        }

        public Criteria andAStartTimeBetween(Date value1, Date value2) {
            addCriterion("a_start_time between", value1, value2, "aStartTime");
            return (Criteria) this;
        }

        public Criteria andAStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("a_start_time not between", value1, value2, "aStartTime");
            return (Criteria) this;
        }

        public Criteria andAEndTimeIsNull() {
            addCriterion("a_end_time is null");
            return (Criteria) this;
        }

        public Criteria andAEndTimeIsNotNull() {
            addCriterion("a_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andAEndTimeEqualTo(Date value) {
            addCriterion("a_end_time =", value, "aEndTime");
            return (Criteria) this;
        }

        public Criteria andAEndTimeNotEqualTo(Date value) {
            addCriterion("a_end_time <>", value, "aEndTime");
            return (Criteria) this;
        }

        public Criteria andAEndTimeGreaterThan(Date value) {
            addCriterion("a_end_time >", value, "aEndTime");
            return (Criteria) this;
        }

        public Criteria andAEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("a_end_time >=", value, "aEndTime");
            return (Criteria) this;
        }

        public Criteria andAEndTimeLessThan(Date value) {
            addCriterion("a_end_time <", value, "aEndTime");
            return (Criteria) this;
        }

        public Criteria andAEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("a_end_time <=", value, "aEndTime");
            return (Criteria) this;
        }

        public Criteria andAEndTimeIn(List<Date> values) {
            addCriterion("a_end_time in", values, "aEndTime");
            return (Criteria) this;
        }

        public Criteria andAEndTimeNotIn(List<Date> values) {
            addCriterion("a_end_time not in", values, "aEndTime");
            return (Criteria) this;
        }

        public Criteria andAEndTimeBetween(Date value1, Date value2) {
            addCriterion("a_end_time between", value1, value2, "aEndTime");
            return (Criteria) this;
        }

        public Criteria andAEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("a_end_time not between", value1, value2, "aEndTime");
            return (Criteria) this;
        }

        public Criteria andAAddressIsNull() {
            addCriterion("a_address is null");
            return (Criteria) this;
        }

        public Criteria andAAddressIsNotNull() {
            addCriterion("a_address is not null");
            return (Criteria) this;
        }

        public Criteria andAAddressEqualTo(String value) {
            addCriterion("a_address =", value, "aAddress");
            return (Criteria) this;
        }

        public Criteria andAAddressNotEqualTo(String value) {
            addCriterion("a_address <>", value, "aAddress");
            return (Criteria) this;
        }

        public Criteria andAAddressGreaterThan(String value) {
            addCriterion("a_address >", value, "aAddress");
            return (Criteria) this;
        }

        public Criteria andAAddressGreaterThanOrEqualTo(String value) {
            addCriterion("a_address >=", value, "aAddress");
            return (Criteria) this;
        }

        public Criteria andAAddressLessThan(String value) {
            addCriterion("a_address <", value, "aAddress");
            return (Criteria) this;
        }

        public Criteria andAAddressLessThanOrEqualTo(String value) {
            addCriterion("a_address <=", value, "aAddress");
            return (Criteria) this;
        }

        public Criteria andAAddressLike(String value) {
            addCriterion("a_address like", value, "aAddress");
            return (Criteria) this;
        }

        public Criteria andAAddressNotLike(String value) {
            addCriterion("a_address not like", value, "aAddress");
            return (Criteria) this;
        }

        public Criteria andAAddressIn(List<String> values) {
            addCriterion("a_address in", values, "aAddress");
            return (Criteria) this;
        }

        public Criteria andAAddressNotIn(List<String> values) {
            addCriterion("a_address not in", values, "aAddress");
            return (Criteria) this;
        }

        public Criteria andAAddressBetween(String value1, String value2) {
            addCriterion("a_address between", value1, value2, "aAddress");
            return (Criteria) this;
        }

        public Criteria andAAddressNotBetween(String value1, String value2) {
            addCriterion("a_address not between", value1, value2, "aAddress");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexBigUrlIsNull() {
            addCriterion("a_photo_index_big_url is null");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexBigUrlIsNotNull() {
            addCriterion("a_photo_index_big_url is not null");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexBigUrlEqualTo(String value) {
            addCriterion("a_photo_index_big_url =", value, "aPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexBigUrlNotEqualTo(String value) {
            addCriterion("a_photo_index_big_url <>", value, "aPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexBigUrlGreaterThan(String value) {
            addCriterion("a_photo_index_big_url >", value, "aPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexBigUrlGreaterThanOrEqualTo(String value) {
            addCriterion("a_photo_index_big_url >=", value, "aPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexBigUrlLessThan(String value) {
            addCriterion("a_photo_index_big_url <", value, "aPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexBigUrlLessThanOrEqualTo(String value) {
            addCriterion("a_photo_index_big_url <=", value, "aPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexBigUrlLike(String value) {
            addCriterion("a_photo_index_big_url like", value, "aPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexBigUrlNotLike(String value) {
            addCriterion("a_photo_index_big_url not like", value, "aPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexBigUrlIn(List<String> values) {
            addCriterion("a_photo_index_big_url in", values, "aPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexBigUrlNotIn(List<String> values) {
            addCriterion("a_photo_index_big_url not in", values, "aPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexBigUrlBetween(String value1, String value2) {
            addCriterion("a_photo_index_big_url between", value1, value2, "aPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexBigUrlNotBetween(String value1, String value2) {
            addCriterion("a_photo_index_big_url not between", value1, value2, "aPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexSmUrlIsNull() {
            addCriterion("a_photo_index_sm_url is null");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexSmUrlIsNotNull() {
            addCriterion("a_photo_index_sm_url is not null");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexSmUrlEqualTo(String value) {
            addCriterion("a_photo_index_sm_url =", value, "aPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexSmUrlNotEqualTo(String value) {
            addCriterion("a_photo_index_sm_url <>", value, "aPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexSmUrlGreaterThan(String value) {
            addCriterion("a_photo_index_sm_url >", value, "aPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexSmUrlGreaterThanOrEqualTo(String value) {
            addCriterion("a_photo_index_sm_url >=", value, "aPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexSmUrlLessThan(String value) {
            addCriterion("a_photo_index_sm_url <", value, "aPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexSmUrlLessThanOrEqualTo(String value) {
            addCriterion("a_photo_index_sm_url <=", value, "aPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexSmUrlLike(String value) {
            addCriterion("a_photo_index_sm_url like", value, "aPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexSmUrlNotLike(String value) {
            addCriterion("a_photo_index_sm_url not like", value, "aPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexSmUrlIn(List<String> values) {
            addCriterion("a_photo_index_sm_url in", values, "aPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexSmUrlNotIn(List<String> values) {
            addCriterion("a_photo_index_sm_url not in", values, "aPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexSmUrlBetween(String value1, String value2) {
            addCriterion("a_photo_index_sm_url between", value1, value2, "aPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoIndexSmUrlNotBetween(String value1, String value2) {
            addCriterion("a_photo_index_sm_url not between", value1, value2, "aPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoUrlIsNull() {
            addCriterion("a_photo_url is null");
            return (Criteria) this;
        }

        public Criteria andAPhotoUrlIsNotNull() {
            addCriterion("a_photo_url is not null");
            return (Criteria) this;
        }

        public Criteria andAPhotoUrlEqualTo(String value) {
            addCriterion("a_photo_url =", value, "aPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoUrlNotEqualTo(String value) {
            addCriterion("a_photo_url <>", value, "aPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoUrlGreaterThan(String value) {
            addCriterion("a_photo_url >", value, "aPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoUrlGreaterThanOrEqualTo(String value) {
            addCriterion("a_photo_url >=", value, "aPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoUrlLessThan(String value) {
            addCriterion("a_photo_url <", value, "aPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoUrlLessThanOrEqualTo(String value) {
            addCriterion("a_photo_url <=", value, "aPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoUrlLike(String value) {
            addCriterion("a_photo_url like", value, "aPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoUrlNotLike(String value) {
            addCriterion("a_photo_url not like", value, "aPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoUrlIn(List<String> values) {
            addCriterion("a_photo_url in", values, "aPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoUrlNotIn(List<String> values) {
            addCriterion("a_photo_url not in", values, "aPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoUrlBetween(String value1, String value2) {
            addCriterion("a_photo_url between", value1, value2, "aPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andAPhotoUrlNotBetween(String value1, String value2) {
            addCriterion("a_photo_url not between", value1, value2, "aPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andAIntroduceIsNull() {
            addCriterion("a_introduce is null");
            return (Criteria) this;
        }

        public Criteria andAIntroduceIsNotNull() {
            addCriterion("a_introduce is not null");
            return (Criteria) this;
        }

        public Criteria andAIntroduceEqualTo(String value) {
            addCriterion("a_introduce =", value, "aIntroduce");
            return (Criteria) this;
        }

        public Criteria andAIntroduceNotEqualTo(String value) {
            addCriterion("a_introduce <>", value, "aIntroduce");
            return (Criteria) this;
        }

        public Criteria andAIntroduceGreaterThan(String value) {
            addCriterion("a_introduce >", value, "aIntroduce");
            return (Criteria) this;
        }

        public Criteria andAIntroduceGreaterThanOrEqualTo(String value) {
            addCriterion("a_introduce >=", value, "aIntroduce");
            return (Criteria) this;
        }

        public Criteria andAIntroduceLessThan(String value) {
            addCriterion("a_introduce <", value, "aIntroduce");
            return (Criteria) this;
        }

        public Criteria andAIntroduceLessThanOrEqualTo(String value) {
            addCriterion("a_introduce <=", value, "aIntroduce");
            return (Criteria) this;
        }

        public Criteria andAIntroduceLike(String value) {
            addCriterion("a_introduce like", value, "aIntroduce");
            return (Criteria) this;
        }

        public Criteria andAIntroduceNotLike(String value) {
            addCriterion("a_introduce not like", value, "aIntroduce");
            return (Criteria) this;
        }

        public Criteria andAIntroduceIn(List<String> values) {
            addCriterion("a_introduce in", values, "aIntroduce");
            return (Criteria) this;
        }

        public Criteria andAIntroduceNotIn(List<String> values) {
            addCriterion("a_introduce not in", values, "aIntroduce");
            return (Criteria) this;
        }

        public Criteria andAIntroduceBetween(String value1, String value2) {
            addCriterion("a_introduce between", value1, value2, "aIntroduce");
            return (Criteria) this;
        }

        public Criteria andAIntroduceNotBetween(String value1, String value2) {
            addCriterion("a_introduce not between", value1, value2, "aIntroduce");
            return (Criteria) this;
        }

        public Criteria andAFlagIsNull() {
            addCriterion("a_flag is null");
            return (Criteria) this;
        }

        public Criteria andAFlagIsNotNull() {
            addCriterion("a_flag is not null");
            return (Criteria) this;
        }

        public Criteria andAFlagEqualTo(Integer value) {
            addCriterion("a_flag =", value, "aFlag");
            return (Criteria) this;
        }

        public Criteria andAFlagNotEqualTo(Integer value) {
            addCriterion("a_flag <>", value, "aFlag");
            return (Criteria) this;
        }

        public Criteria andAFlagGreaterThan(Integer value) {
            addCriterion("a_flag >", value, "aFlag");
            return (Criteria) this;
        }

        public Criteria andAFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("a_flag >=", value, "aFlag");
            return (Criteria) this;
        }

        public Criteria andAFlagLessThan(Integer value) {
            addCriterion("a_flag <", value, "aFlag");
            return (Criteria) this;
        }

        public Criteria andAFlagLessThanOrEqualTo(Integer value) {
            addCriterion("a_flag <=", value, "aFlag");
            return (Criteria) this;
        }

        public Criteria andAFlagIn(List<Integer> values) {
            addCriterion("a_flag in", values, "aFlag");
            return (Criteria) this;
        }

        public Criteria andAFlagNotIn(List<Integer> values) {
            addCriterion("a_flag not in", values, "aFlag");
            return (Criteria) this;
        }

        public Criteria andAFlagBetween(Integer value1, Integer value2) {
            addCriterion("a_flag between", value1, value2, "aFlag");
            return (Criteria) this;
        }

        public Criteria andAFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("a_flag not between", value1, value2, "aFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_activity
     *
     * @mbg.generated do_not_delete_during_merge Mon Feb 01 12:56:39 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_activity
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}