package com.hoperun.pesystem.model;

import java.io.Serializable;

public class Admin implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.admin_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.admin_username
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private String adminUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.admin_password
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private String adminPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.admin_caption_url
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private String adminCaptionUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.admin_id
     *
     * @return the value of t_admin.admin_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.admin_id
     *
     * @param adminId the value for t_admin.admin_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.admin_username
     *
     * @return the value of t_admin.admin_username
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getAdminUsername() {
        return adminUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.admin_username
     *
     * @param adminUsername the value for t_admin.admin_username
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setAdminUsername(String adminUsername) {
        this.adminUsername = adminUsername == null ? null : adminUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.admin_password
     *
     * @return the value of t_admin.admin_password
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getAdminPassword() {
        return adminPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.admin_password
     *
     * @param adminPassword the value for t_admin.admin_password
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword == null ? null : adminPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.admin_caption_url
     *
     * @return the value of t_admin.admin_caption_url
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getAdminCaptionUrl() {
        return adminCaptionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.admin_caption_url
     *
     * @param adminCaptionUrl the value for t_admin.admin_caption_url
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setAdminCaptionUrl(String adminCaptionUrl) {
        this.adminCaptionUrl = adminCaptionUrl == null ? null : adminCaptionUrl.trim();
    }
}