package com.hoperun.pesystem.model;

import java.io.Serializable;

public class Browse  implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_browse.browse_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Integer browseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_browse.browse_type_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Integer browseTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_browse.browse_user_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Integer browseUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_browse.browse_id
     *
     * @return the value of t_browse.browse_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Integer getBrowseId() {
        return browseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_browse.browse_id
     *
     * @param browseId the value for t_browse.browse_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setBrowseId(Integer browseId) {
        this.browseId = browseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_browse.browse_type_id
     *
     * @return the value of t_browse.browse_type_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Integer getBrowseTypeId() {
        return browseTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_browse.browse_type_id
     *
     * @param browseTypeId the value for t_browse.browse_type_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setBrowseTypeId(Integer browseTypeId) {
        this.browseTypeId = browseTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_browse.browse_user_id
     *
     * @return the value of t_browse.browse_user_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Integer getBrowseUserId() {
        return browseUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_browse.browse_user_id
     *
     * @param browseUserId the value for t_browse.browse_user_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setBrowseUserId(Integer browseUserId) {
        this.browseUserId = browseUserId;
    }
}