package com.hoperun.pesystem.model;

import java.util.ArrayList;
import java.util.List;

public class BrowseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public BrowseExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBrowseIdIsNull() {
            addCriterion("browse_id is null");
            return (Criteria) this;
        }

        public Criteria andBrowseIdIsNotNull() {
            addCriterion("browse_id is not null");
            return (Criteria) this;
        }

        public Criteria andBrowseIdEqualTo(Integer value) {
            addCriterion("browse_id =", value, "browseId");
            return (Criteria) this;
        }

        public Criteria andBrowseIdNotEqualTo(Integer value) {
            addCriterion("browse_id <>", value, "browseId");
            return (Criteria) this;
        }

        public Criteria andBrowseIdGreaterThan(Integer value) {
            addCriterion("browse_id >", value, "browseId");
            return (Criteria) this;
        }

        public Criteria andBrowseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("browse_id >=", value, "browseId");
            return (Criteria) this;
        }

        public Criteria andBrowseIdLessThan(Integer value) {
            addCriterion("browse_id <", value, "browseId");
            return (Criteria) this;
        }

        public Criteria andBrowseIdLessThanOrEqualTo(Integer value) {
            addCriterion("browse_id <=", value, "browseId");
            return (Criteria) this;
        }

        public Criteria andBrowseIdIn(List<Integer> values) {
            addCriterion("browse_id in", values, "browseId");
            return (Criteria) this;
        }

        public Criteria andBrowseIdNotIn(List<Integer> values) {
            addCriterion("browse_id not in", values, "browseId");
            return (Criteria) this;
        }

        public Criteria andBrowseIdBetween(Integer value1, Integer value2) {
            addCriterion("browse_id between", value1, value2, "browseId");
            return (Criteria) this;
        }

        public Criteria andBrowseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("browse_id not between", value1, value2, "browseId");
            return (Criteria) this;
        }

        public Criteria andBrowseTypeIdIsNull() {
            addCriterion("browse_type_id is null");
            return (Criteria) this;
        }

        public Criteria andBrowseTypeIdIsNotNull() {
            addCriterion("browse_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andBrowseTypeIdEqualTo(Integer value) {
            addCriterion("browse_type_id =", value, "browseTypeId");
            return (Criteria) this;
        }

        public Criteria andBrowseTypeIdNotEqualTo(Integer value) {
            addCriterion("browse_type_id <>", value, "browseTypeId");
            return (Criteria) this;
        }

        public Criteria andBrowseTypeIdGreaterThan(Integer value) {
            addCriterion("browse_type_id >", value, "browseTypeId");
            return (Criteria) this;
        }

        public Criteria andBrowseTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("browse_type_id >=", value, "browseTypeId");
            return (Criteria) this;
        }

        public Criteria andBrowseTypeIdLessThan(Integer value) {
            addCriterion("browse_type_id <", value, "browseTypeId");
            return (Criteria) this;
        }

        public Criteria andBrowseTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("browse_type_id <=", value, "browseTypeId");
            return (Criteria) this;
        }

        public Criteria andBrowseTypeIdIn(List<Integer> values) {
            addCriterion("browse_type_id in", values, "browseTypeId");
            return (Criteria) this;
        }

        public Criteria andBrowseTypeIdNotIn(List<Integer> values) {
            addCriterion("browse_type_id not in", values, "browseTypeId");
            return (Criteria) this;
        }

        public Criteria andBrowseTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("browse_type_id between", value1, value2, "browseTypeId");
            return (Criteria) this;
        }

        public Criteria andBrowseTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("browse_type_id not between", value1, value2, "browseTypeId");
            return (Criteria) this;
        }

        public Criteria andBrowseUserIdIsNull() {
            addCriterion("browse_user_id is null");
            return (Criteria) this;
        }

        public Criteria andBrowseUserIdIsNotNull() {
            addCriterion("browse_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andBrowseUserIdEqualTo(Integer value) {
            addCriterion("browse_user_id =", value, "browseUserId");
            return (Criteria) this;
        }

        public Criteria andBrowseUserIdNotEqualTo(Integer value) {
            addCriterion("browse_user_id <>", value, "browseUserId");
            return (Criteria) this;
        }

        public Criteria andBrowseUserIdGreaterThan(Integer value) {
            addCriterion("browse_user_id >", value, "browseUserId");
            return (Criteria) this;
        }

        public Criteria andBrowseUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("browse_user_id >=", value, "browseUserId");
            return (Criteria) this;
        }

        public Criteria andBrowseUserIdLessThan(Integer value) {
            addCriterion("browse_user_id <", value, "browseUserId");
            return (Criteria) this;
        }

        public Criteria andBrowseUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("browse_user_id <=", value, "browseUserId");
            return (Criteria) this;
        }

        public Criteria andBrowseUserIdIn(List<Integer> values) {
            addCriterion("browse_user_id in", values, "browseUserId");
            return (Criteria) this;
        }

        public Criteria andBrowseUserIdNotIn(List<Integer> values) {
            addCriterion("browse_user_id not in", values, "browseUserId");
            return (Criteria) this;
        }

        public Criteria andBrowseUserIdBetween(Integer value1, Integer value2) {
            addCriterion("browse_user_id between", value1, value2, "browseUserId");
            return (Criteria) this;
        }

        public Criteria andBrowseUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("browse_user_id not between", value1, value2, "browseUserId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_browse
     *
     * @mbg.generated do_not_delete_during_merge Mon Feb 01 12:56:39 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}