package com.hoperun.pesystem.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ExchangeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public ExchangeExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andExIdIsNull() {
            addCriterion("ex_id is null");
            return (Criteria) this;
        }

        public Criteria andExIdIsNotNull() {
            addCriterion("ex_id is not null");
            return (Criteria) this;
        }

        public Criteria andExIdEqualTo(Integer value) {
            addCriterion("ex_id =", value, "exId");
            return (Criteria) this;
        }

        public Criteria andExIdNotEqualTo(Integer value) {
            addCriterion("ex_id <>", value, "exId");
            return (Criteria) this;
        }

        public Criteria andExIdGreaterThan(Integer value) {
            addCriterion("ex_id >", value, "exId");
            return (Criteria) this;
        }

        public Criteria andExIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ex_id >=", value, "exId");
            return (Criteria) this;
        }

        public Criteria andExIdLessThan(Integer value) {
            addCriterion("ex_id <", value, "exId");
            return (Criteria) this;
        }

        public Criteria andExIdLessThanOrEqualTo(Integer value) {
            addCriterion("ex_id <=", value, "exId");
            return (Criteria) this;
        }

        public Criteria andExIdIn(List<Integer> values) {
            addCriterion("ex_id in", values, "exId");
            return (Criteria) this;
        }

        public Criteria andExIdNotIn(List<Integer> values) {
            addCriterion("ex_id not in", values, "exId");
            return (Criteria) this;
        }

        public Criteria andExIdBetween(Integer value1, Integer value2) {
            addCriterion("ex_id between", value1, value2, "exId");
            return (Criteria) this;
        }

        public Criteria andExIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ex_id not between", value1, value2, "exId");
            return (Criteria) this;
        }

        public Criteria andExGoodsIdIsNull() {
            addCriterion("ex_goods_id is null");
            return (Criteria) this;
        }

        public Criteria andExGoodsIdIsNotNull() {
            addCriterion("ex_goods_id is not null");
            return (Criteria) this;
        }

        public Criteria andExGoodsIdEqualTo(Integer value) {
            addCriterion("ex_goods_id =", value, "exGoodsId");
            return (Criteria) this;
        }

        public Criteria andExGoodsIdNotEqualTo(Integer value) {
            addCriterion("ex_goods_id <>", value, "exGoodsId");
            return (Criteria) this;
        }

        public Criteria andExGoodsIdGreaterThan(Integer value) {
            addCriterion("ex_goods_id >", value, "exGoodsId");
            return (Criteria) this;
        }

        public Criteria andExGoodsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ex_goods_id >=", value, "exGoodsId");
            return (Criteria) this;
        }

        public Criteria andExGoodsIdLessThan(Integer value) {
            addCriterion("ex_goods_id <", value, "exGoodsId");
            return (Criteria) this;
        }

        public Criteria andExGoodsIdLessThanOrEqualTo(Integer value) {
            addCriterion("ex_goods_id <=", value, "exGoodsId");
            return (Criteria) this;
        }

        public Criteria andExGoodsIdIn(List<Integer> values) {
            addCriterion("ex_goods_id in", values, "exGoodsId");
            return (Criteria) this;
        }

        public Criteria andExGoodsIdNotIn(List<Integer> values) {
            addCriterion("ex_goods_id not in", values, "exGoodsId");
            return (Criteria) this;
        }

        public Criteria andExGoodsIdBetween(Integer value1, Integer value2) {
            addCriterion("ex_goods_id between", value1, value2, "exGoodsId");
            return (Criteria) this;
        }

        public Criteria andExGoodsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ex_goods_id not between", value1, value2, "exGoodsId");
            return (Criteria) this;
        }

        public Criteria andExTimeIsNull() {
            addCriterion("ex_time is null");
            return (Criteria) this;
        }

        public Criteria andExTimeIsNotNull() {
            addCriterion("ex_time is not null");
            return (Criteria) this;
        }

        public Criteria andExTimeEqualTo(Date value) {
            addCriterion("ex_time =", value, "exTime");
            return (Criteria) this;
        }

        public Criteria andExTimeNotEqualTo(Date value) {
            addCriterion("ex_time <>", value, "exTime");
            return (Criteria) this;
        }

        public Criteria andExTimeGreaterThan(Date value) {
            addCriterion("ex_time >", value, "exTime");
            return (Criteria) this;
        }

        public Criteria andExTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ex_time >=", value, "exTime");
            return (Criteria) this;
        }

        public Criteria andExTimeLessThan(Date value) {
            addCriterion("ex_time <", value, "exTime");
            return (Criteria) this;
        }

        public Criteria andExTimeLessThanOrEqualTo(Date value) {
            addCriterion("ex_time <=", value, "exTime");
            return (Criteria) this;
        }

        public Criteria andExTimeIn(List<Date> values) {
            addCriterion("ex_time in", values, "exTime");
            return (Criteria) this;
        }

        public Criteria andExTimeNotIn(List<Date> values) {
            addCriterion("ex_time not in", values, "exTime");
            return (Criteria) this;
        }

        public Criteria andExTimeBetween(Date value1, Date value2) {
            addCriterion("ex_time between", value1, value2, "exTime");
            return (Criteria) this;
        }

        public Criteria andExTimeNotBetween(Date value1, Date value2) {
            addCriterion("ex_time not between", value1, value2, "exTime");
            return (Criteria) this;
        }

        public Criteria andExGoodsNameIsNull() {
            addCriterion("ex_goods_name is null");
            return (Criteria) this;
        }

        public Criteria andExGoodsNameIsNotNull() {
            addCriterion("ex_goods_name is not null");
            return (Criteria) this;
        }

        public Criteria andExGoodsNameEqualTo(String value) {
            addCriterion("ex_goods_name =", value, "exGoodsName");
            return (Criteria) this;
        }

        public Criteria andExGoodsNameNotEqualTo(String value) {
            addCriterion("ex_goods_name <>", value, "exGoodsName");
            return (Criteria) this;
        }

        public Criteria andExGoodsNameGreaterThan(String value) {
            addCriterion("ex_goods_name >", value, "exGoodsName");
            return (Criteria) this;
        }

        public Criteria andExGoodsNameGreaterThanOrEqualTo(String value) {
            addCriterion("ex_goods_name >=", value, "exGoodsName");
            return (Criteria) this;
        }

        public Criteria andExGoodsNameLessThan(String value) {
            addCriterion("ex_goods_name <", value, "exGoodsName");
            return (Criteria) this;
        }

        public Criteria andExGoodsNameLessThanOrEqualTo(String value) {
            addCriterion("ex_goods_name <=", value, "exGoodsName");
            return (Criteria) this;
        }

        public Criteria andExGoodsNameLike(String value) {
            addCriterion("ex_goods_name like", value, "exGoodsName");
            return (Criteria) this;
        }

        public Criteria andExGoodsNameNotLike(String value) {
            addCriterion("ex_goods_name not like", value, "exGoodsName");
            return (Criteria) this;
        }

        public Criteria andExGoodsNameIn(List<String> values) {
            addCriterion("ex_goods_name in", values, "exGoodsName");
            return (Criteria) this;
        }

        public Criteria andExGoodsNameNotIn(List<String> values) {
            addCriterion("ex_goods_name not in", values, "exGoodsName");
            return (Criteria) this;
        }

        public Criteria andExGoodsNameBetween(String value1, String value2) {
            addCriterion("ex_goods_name between", value1, value2, "exGoodsName");
            return (Criteria) this;
        }

        public Criteria andExGoodsNameNotBetween(String value1, String value2) {
            addCriterion("ex_goods_name not between", value1, value2, "exGoodsName");
            return (Criteria) this;
        }

        public Criteria andExGoodsIntegralIsNull() {
            addCriterion("ex_goods_integral is null");
            return (Criteria) this;
        }

        public Criteria andExGoodsIntegralIsNotNull() {
            addCriterion("ex_goods_integral is not null");
            return (Criteria) this;
        }

        public Criteria andExGoodsIntegralEqualTo(Integer value) {
            addCriterion("ex_goods_integral =", value, "exGoodsIntegral");
            return (Criteria) this;
        }

        public Criteria andExGoodsIntegralNotEqualTo(Integer value) {
            addCriterion("ex_goods_integral <>", value, "exGoodsIntegral");
            return (Criteria) this;
        }

        public Criteria andExGoodsIntegralGreaterThan(Integer value) {
            addCriterion("ex_goods_integral >", value, "exGoodsIntegral");
            return (Criteria) this;
        }

        public Criteria andExGoodsIntegralGreaterThanOrEqualTo(Integer value) {
            addCriterion("ex_goods_integral >=", value, "exGoodsIntegral");
            return (Criteria) this;
        }

        public Criteria andExGoodsIntegralLessThan(Integer value) {
            addCriterion("ex_goods_integral <", value, "exGoodsIntegral");
            return (Criteria) this;
        }

        public Criteria andExGoodsIntegralLessThanOrEqualTo(Integer value) {
            addCriterion("ex_goods_integral <=", value, "exGoodsIntegral");
            return (Criteria) this;
        }

        public Criteria andExGoodsIntegralIn(List<Integer> values) {
            addCriterion("ex_goods_integral in", values, "exGoodsIntegral");
            return (Criteria) this;
        }

        public Criteria andExGoodsIntegralNotIn(List<Integer> values) {
            addCriterion("ex_goods_integral not in", values, "exGoodsIntegral");
            return (Criteria) this;
        }

        public Criteria andExGoodsIntegralBetween(Integer value1, Integer value2) {
            addCriterion("ex_goods_integral between", value1, value2, "exGoodsIntegral");
            return (Criteria) this;
        }

        public Criteria andExGoodsIntegralNotBetween(Integer value1, Integer value2) {
            addCriterion("ex_goods_integral not between", value1, value2, "exGoodsIntegral");
            return (Criteria) this;
        }

        public Criteria andExNumIsNull() {
            addCriterion("ex_num is null");
            return (Criteria) this;
        }

        public Criteria andExNumIsNotNull() {
            addCriterion("ex_num is not null");
            return (Criteria) this;
        }

        public Criteria andExNumEqualTo(Integer value) {
            addCriterion("ex_num =", value, "exNum");
            return (Criteria) this;
        }

        public Criteria andExNumNotEqualTo(Integer value) {
            addCriterion("ex_num <>", value, "exNum");
            return (Criteria) this;
        }

        public Criteria andExNumGreaterThan(Integer value) {
            addCriterion("ex_num >", value, "exNum");
            return (Criteria) this;
        }

        public Criteria andExNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("ex_num >=", value, "exNum");
            return (Criteria) this;
        }

        public Criteria andExNumLessThan(Integer value) {
            addCriterion("ex_num <", value, "exNum");
            return (Criteria) this;
        }

        public Criteria andExNumLessThanOrEqualTo(Integer value) {
            addCriterion("ex_num <=", value, "exNum");
            return (Criteria) this;
        }

        public Criteria andExNumIn(List<Integer> values) {
            addCriterion("ex_num in", values, "exNum");
            return (Criteria) this;
        }

        public Criteria andExNumNotIn(List<Integer> values) {
            addCriterion("ex_num not in", values, "exNum");
            return (Criteria) this;
        }

        public Criteria andExNumBetween(Integer value1, Integer value2) {
            addCriterion("ex_num between", value1, value2, "exNum");
            return (Criteria) this;
        }

        public Criteria andExNumNotBetween(Integer value1, Integer value2) {
            addCriterion("ex_num not between", value1, value2, "exNum");
            return (Criteria) this;
        }

        public Criteria andExUserIdIsNull() {
            addCriterion("ex_user_id is null");
            return (Criteria) this;
        }

        public Criteria andExUserIdIsNotNull() {
            addCriterion("ex_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andExUserIdEqualTo(Integer value) {
            addCriterion("ex_user_id =", value, "exUserId");
            return (Criteria) this;
        }

        public Criteria andExUserIdNotEqualTo(Integer value) {
            addCriterion("ex_user_id <>", value, "exUserId");
            return (Criteria) this;
        }

        public Criteria andExUserIdGreaterThan(Integer value) {
            addCriterion("ex_user_id >", value, "exUserId");
            return (Criteria) this;
        }

        public Criteria andExUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ex_user_id >=", value, "exUserId");
            return (Criteria) this;
        }

        public Criteria andExUserIdLessThan(Integer value) {
            addCriterion("ex_user_id <", value, "exUserId");
            return (Criteria) this;
        }

        public Criteria andExUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("ex_user_id <=", value, "exUserId");
            return (Criteria) this;
        }

        public Criteria andExUserIdIn(List<Integer> values) {
            addCriterion("ex_user_id in", values, "exUserId");
            return (Criteria) this;
        }

        public Criteria andExUserIdNotIn(List<Integer> values) {
            addCriterion("ex_user_id not in", values, "exUserId");
            return (Criteria) this;
        }

        public Criteria andExUserIdBetween(Integer value1, Integer value2) {
            addCriterion("ex_user_id between", value1, value2, "exUserId");
            return (Criteria) this;
        }

        public Criteria andExUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ex_user_id not between", value1, value2, "exUserId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_exchange
     *
     * @mbg.generated do_not_delete_during_merge Mon Feb 01 12:56:39 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}