package com.hoperun.pesystem.model;

import java.io.Serializable;
import java.util.Date;

public class Exchange  implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exchange.ex_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Integer exId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exchange.ex_goods_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Integer exGoodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exchange.ex_time
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Date exTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exchange.ex_goods_name
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private String exGoodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exchange.ex_goods_integral
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Integer exGoodsIntegral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exchange.ex_num
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Integer exNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exchange.ex_user_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Integer exUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exchange.ex_id
     *
     * @return the value of t_exchange.ex_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Integer getExId() {
        return exId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exchange.ex_id
     *
     * @param exId the value for t_exchange.ex_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setExId(Integer exId) {
        this.exId = exId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exchange.ex_goods_id
     *
     * @return the value of t_exchange.ex_goods_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Integer getExGoodsId() {
        return exGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exchange.ex_goods_id
     *
     * @param exGoodsId the value for t_exchange.ex_goods_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setExGoodsId(Integer exGoodsId) {
        this.exGoodsId = exGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exchange.ex_time
     *
     * @return the value of t_exchange.ex_time
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Date getExTime() {
        return exTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exchange.ex_time
     *
     * @param exTime the value for t_exchange.ex_time
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setExTime(Date exTime) {
        this.exTime = exTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exchange.ex_goods_name
     *
     * @return the value of t_exchange.ex_goods_name
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getExGoodsName() {
        return exGoodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exchange.ex_goods_name
     *
     * @param exGoodsName the value for t_exchange.ex_goods_name
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setExGoodsName(String exGoodsName) {
        this.exGoodsName = exGoodsName == null ? null : exGoodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exchange.ex_goods_integral
     *
     * @return the value of t_exchange.ex_goods_integral
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Integer getExGoodsIntegral() {
        return exGoodsIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exchange.ex_goods_integral
     *
     * @param exGoodsIntegral the value for t_exchange.ex_goods_integral
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setExGoodsIntegral(Integer exGoodsIntegral) {
        this.exGoodsIntegral = exGoodsIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exchange.ex_num
     *
     * @return the value of t_exchange.ex_num
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Integer getExNum() {
        return exNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exchange.ex_num
     *
     * @param exNum the value for t_exchange.ex_num
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setExNum(Integer exNum) {
        this.exNum = exNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exchange.ex_user_id
     *
     * @return the value of t_exchange.ex_user_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Integer getExUserId() {
        return exUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exchange.ex_user_id
     *
     * @param exUserId the value for t_exchange.ex_user_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setExUserId(Integer exUserId) {
        this.exUserId = exUserId;
    }
}