package com.hoperun.pesystem.model;

import java.io.Serializable;
import java.util.Date;

public class Goods implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_name
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_type_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Integer goodsTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_integral
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Integer goodsIntegral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_photo_index_big_url
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private String goodsPhotoIndexBigUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_photo_index_sm_url
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private String goodsPhotoIndexSmUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_photo_url
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private String goodsPhotoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_start_time
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Date goodsStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_end_time
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Date goodsEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_introduce
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private String goodsIntroduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_flag
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Integer goodsFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_infromation
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private String goodsInfromation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_id
     *
     * @return the value of t_goods.goods_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_id
     *
     * @param goodsId the value for t_goods.goods_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_name
     *
     * @return the value of t_goods.goods_name
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_name
     *
     * @param goodsName the value for t_goods.goods_name
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_type_id
     *
     * @return the value of t_goods.goods_type_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Integer getGoodsTypeId() {
        return goodsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_type_id
     *
     * @param goodsTypeId the value for t_goods.goods_type_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setGoodsTypeId(Integer goodsTypeId) {
        this.goodsTypeId = goodsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_integral
     *
     * @return the value of t_goods.goods_integral
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Integer getGoodsIntegral() {
        return goodsIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_integral
     *
     * @param goodsIntegral the value for t_goods.goods_integral
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setGoodsIntegral(Integer goodsIntegral) {
        this.goodsIntegral = goodsIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_photo_index_big_url
     *
     * @return the value of t_goods.goods_photo_index_big_url
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getGoodsPhotoIndexBigUrl() {
        return goodsPhotoIndexBigUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_photo_index_big_url
     *
     * @param goodsPhotoIndexBigUrl the value for t_goods.goods_photo_index_big_url
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setGoodsPhotoIndexBigUrl(String goodsPhotoIndexBigUrl) {
        this.goodsPhotoIndexBigUrl = goodsPhotoIndexBigUrl == null ? null : goodsPhotoIndexBigUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_photo_index_sm_url
     *
     * @return the value of t_goods.goods_photo_index_sm_url
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getGoodsPhotoIndexSmUrl() {
        return goodsPhotoIndexSmUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_photo_index_sm_url
     *
     * @param goodsPhotoIndexSmUrl the value for t_goods.goods_photo_index_sm_url
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setGoodsPhotoIndexSmUrl(String goodsPhotoIndexSmUrl) {
        this.goodsPhotoIndexSmUrl = goodsPhotoIndexSmUrl == null ? null : goodsPhotoIndexSmUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_photo_url
     *
     * @return the value of t_goods.goods_photo_url
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getGoodsPhotoUrl() {
        return goodsPhotoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_photo_url
     *
     * @param goodsPhotoUrl the value for t_goods.goods_photo_url
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setGoodsPhotoUrl(String goodsPhotoUrl) {
        this.goodsPhotoUrl = goodsPhotoUrl == null ? null : goodsPhotoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_start_time
     *
     * @return the value of t_goods.goods_start_time
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Date getGoodsStartTime() {
        return goodsStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_start_time
     *
     * @param goodsStartTime the value for t_goods.goods_start_time
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setGoodsStartTime(Date goodsStartTime) {
        this.goodsStartTime = goodsStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_end_time
     *
     * @return the value of t_goods.goods_end_time
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Date getGoodsEndTime() {
        return goodsEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_end_time
     *
     * @param goodsEndTime the value for t_goods.goods_end_time
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setGoodsEndTime(Date goodsEndTime) {
        this.goodsEndTime = goodsEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_introduce
     *
     * @return the value of t_goods.goods_introduce
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getGoodsIntroduce() {
        return goodsIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_introduce
     *
     * @param goodsIntroduce the value for t_goods.goods_introduce
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setGoodsIntroduce(String goodsIntroduce) {
        this.goodsIntroduce = goodsIntroduce == null ? null : goodsIntroduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_flag
     *
     * @return the value of t_goods.goods_flag
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Integer getGoodsFlag() {
        return goodsFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_flag
     *
     * @param goodsFlag the value for t_goods.goods_flag
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setGoodsFlag(Integer goodsFlag) {
        this.goodsFlag = goodsFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_infromation
     *
     * @return the value of t_goods.goods_infromation
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getGoodsInfromation() {
        return goodsInfromation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_infromation
     *
     * @param goodsInfromation the value for t_goods.goods_infromation
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setGoodsInfromation(String goodsInfromation) {
        this.goodsInfromation = goodsInfromation == null ? null : goodsInfromation.trim();
    }
}