package com.hoperun.pesystem.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GoodsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_goods
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_goods
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_goods
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public GoodsExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_goods
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGoodsIdIsNull() {
            addCriterion("goods_id is null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNotNull() {
            addCriterion("goods_id is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdEqualTo(Integer value) {
            addCriterion("goods_id =", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotEqualTo(Integer value) {
            addCriterion("goods_id <>", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThan(Integer value) {
            addCriterion("goods_id >", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("goods_id >=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThan(Integer value) {
            addCriterion("goods_id <", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThanOrEqualTo(Integer value) {
            addCriterion("goods_id <=", value, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIn(List<Integer> values) {
            addCriterion("goods_id in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotIn(List<Integer> values) {
            addCriterion("goods_id not in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdBetween(Integer value1, Integer value2) {
            addCriterion("goods_id between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("goods_id not between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIsNull() {
            addCriterion("goods_name is null");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIsNotNull() {
            addCriterion("goods_name is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsNameEqualTo(String value) {
            addCriterion("goods_name =", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotEqualTo(String value) {
            addCriterion("goods_name <>", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameGreaterThan(String value) {
            addCriterion("goods_name >", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameGreaterThanOrEqualTo(String value) {
            addCriterion("goods_name >=", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLessThan(String value) {
            addCriterion("goods_name <", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLessThanOrEqualTo(String value) {
            addCriterion("goods_name <=", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLike(String value) {
            addCriterion("goods_name like", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotLike(String value) {
            addCriterion("goods_name not like", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIn(List<String> values) {
            addCriterion("goods_name in", values, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotIn(List<String> values) {
            addCriterion("goods_name not in", values, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameBetween(String value1, String value2) {
            addCriterion("goods_name between", value1, value2, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotBetween(String value1, String value2) {
            addCriterion("goods_name not between", value1, value2, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeIdIsNull() {
            addCriterion("goods_type_id is null");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeIdIsNotNull() {
            addCriterion("goods_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeIdEqualTo(Integer value) {
            addCriterion("goods_type_id =", value, "goodsTypeId");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeIdNotEqualTo(Integer value) {
            addCriterion("goods_type_id <>", value, "goodsTypeId");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeIdGreaterThan(Integer value) {
            addCriterion("goods_type_id >", value, "goodsTypeId");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("goods_type_id >=", value, "goodsTypeId");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeIdLessThan(Integer value) {
            addCriterion("goods_type_id <", value, "goodsTypeId");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("goods_type_id <=", value, "goodsTypeId");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeIdIn(List<Integer> values) {
            addCriterion("goods_type_id in", values, "goodsTypeId");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeIdNotIn(List<Integer> values) {
            addCriterion("goods_type_id not in", values, "goodsTypeId");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("goods_type_id between", value1, value2, "goodsTypeId");
            return (Criteria) this;
        }

        public Criteria andGoodsTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("goods_type_id not between", value1, value2, "goodsTypeId");
            return (Criteria) this;
        }

        public Criteria andGoodsIntegralIsNull() {
            addCriterion("goods_integral is null");
            return (Criteria) this;
        }

        public Criteria andGoodsIntegralIsNotNull() {
            addCriterion("goods_integral is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsIntegralEqualTo(Integer value) {
            addCriterion("goods_integral =", value, "goodsIntegral");
            return (Criteria) this;
        }

        public Criteria andGoodsIntegralNotEqualTo(Integer value) {
            addCriterion("goods_integral <>", value, "goodsIntegral");
            return (Criteria) this;
        }

        public Criteria andGoodsIntegralGreaterThan(Integer value) {
            addCriterion("goods_integral >", value, "goodsIntegral");
            return (Criteria) this;
        }

        public Criteria andGoodsIntegralGreaterThanOrEqualTo(Integer value) {
            addCriterion("goods_integral >=", value, "goodsIntegral");
            return (Criteria) this;
        }

        public Criteria andGoodsIntegralLessThan(Integer value) {
            addCriterion("goods_integral <", value, "goodsIntegral");
            return (Criteria) this;
        }

        public Criteria andGoodsIntegralLessThanOrEqualTo(Integer value) {
            addCriterion("goods_integral <=", value, "goodsIntegral");
            return (Criteria) this;
        }

        public Criteria andGoodsIntegralIn(List<Integer> values) {
            addCriterion("goods_integral in", values, "goodsIntegral");
            return (Criteria) this;
        }

        public Criteria andGoodsIntegralNotIn(List<Integer> values) {
            addCriterion("goods_integral not in", values, "goodsIntegral");
            return (Criteria) this;
        }

        public Criteria andGoodsIntegralBetween(Integer value1, Integer value2) {
            addCriterion("goods_integral between", value1, value2, "goodsIntegral");
            return (Criteria) this;
        }

        public Criteria andGoodsIntegralNotBetween(Integer value1, Integer value2) {
            addCriterion("goods_integral not between", value1, value2, "goodsIntegral");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexBigUrlIsNull() {
            addCriterion("goods_photo_index_big_url is null");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexBigUrlIsNotNull() {
            addCriterion("goods_photo_index_big_url is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexBigUrlEqualTo(String value) {
            addCriterion("goods_photo_index_big_url =", value, "goodsPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexBigUrlNotEqualTo(String value) {
            addCriterion("goods_photo_index_big_url <>", value, "goodsPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexBigUrlGreaterThan(String value) {
            addCriterion("goods_photo_index_big_url >", value, "goodsPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexBigUrlGreaterThanOrEqualTo(String value) {
            addCriterion("goods_photo_index_big_url >=", value, "goodsPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexBigUrlLessThan(String value) {
            addCriterion("goods_photo_index_big_url <", value, "goodsPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexBigUrlLessThanOrEqualTo(String value) {
            addCriterion("goods_photo_index_big_url <=", value, "goodsPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexBigUrlLike(String value) {
            addCriterion("goods_photo_index_big_url like", value, "goodsPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexBigUrlNotLike(String value) {
            addCriterion("goods_photo_index_big_url not like", value, "goodsPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexBigUrlIn(List<String> values) {
            addCriterion("goods_photo_index_big_url in", values, "goodsPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexBigUrlNotIn(List<String> values) {
            addCriterion("goods_photo_index_big_url not in", values, "goodsPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexBigUrlBetween(String value1, String value2) {
            addCriterion("goods_photo_index_big_url between", value1, value2, "goodsPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexBigUrlNotBetween(String value1, String value2) {
            addCriterion("goods_photo_index_big_url not between", value1, value2, "goodsPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexSmUrlIsNull() {
            addCriterion("goods_photo_index_sm_url is null");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexSmUrlIsNotNull() {
            addCriterion("goods_photo_index_sm_url is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexSmUrlEqualTo(String value) {
            addCriterion("goods_photo_index_sm_url =", value, "goodsPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexSmUrlNotEqualTo(String value) {
            addCriterion("goods_photo_index_sm_url <>", value, "goodsPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexSmUrlGreaterThan(String value) {
            addCriterion("goods_photo_index_sm_url >", value, "goodsPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexSmUrlGreaterThanOrEqualTo(String value) {
            addCriterion("goods_photo_index_sm_url >=", value, "goodsPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexSmUrlLessThan(String value) {
            addCriterion("goods_photo_index_sm_url <", value, "goodsPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexSmUrlLessThanOrEqualTo(String value) {
            addCriterion("goods_photo_index_sm_url <=", value, "goodsPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexSmUrlLike(String value) {
            addCriterion("goods_photo_index_sm_url like", value, "goodsPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexSmUrlNotLike(String value) {
            addCriterion("goods_photo_index_sm_url not like", value, "goodsPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexSmUrlIn(List<String> values) {
            addCriterion("goods_photo_index_sm_url in", values, "goodsPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexSmUrlNotIn(List<String> values) {
            addCriterion("goods_photo_index_sm_url not in", values, "goodsPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexSmUrlBetween(String value1, String value2) {
            addCriterion("goods_photo_index_sm_url between", value1, value2, "goodsPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoIndexSmUrlNotBetween(String value1, String value2) {
            addCriterion("goods_photo_index_sm_url not between", value1, value2, "goodsPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoUrlIsNull() {
            addCriterion("goods_photo_url is null");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoUrlIsNotNull() {
            addCriterion("goods_photo_url is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoUrlEqualTo(String value) {
            addCriterion("goods_photo_url =", value, "goodsPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoUrlNotEqualTo(String value) {
            addCriterion("goods_photo_url <>", value, "goodsPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoUrlGreaterThan(String value) {
            addCriterion("goods_photo_url >", value, "goodsPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoUrlGreaterThanOrEqualTo(String value) {
            addCriterion("goods_photo_url >=", value, "goodsPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoUrlLessThan(String value) {
            addCriterion("goods_photo_url <", value, "goodsPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoUrlLessThanOrEqualTo(String value) {
            addCriterion("goods_photo_url <=", value, "goodsPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoUrlLike(String value) {
            addCriterion("goods_photo_url like", value, "goodsPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoUrlNotLike(String value) {
            addCriterion("goods_photo_url not like", value, "goodsPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoUrlIn(List<String> values) {
            addCriterion("goods_photo_url in", values, "goodsPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoUrlNotIn(List<String> values) {
            addCriterion("goods_photo_url not in", values, "goodsPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoUrlBetween(String value1, String value2) {
            addCriterion("goods_photo_url between", value1, value2, "goodsPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsPhotoUrlNotBetween(String value1, String value2) {
            addCriterion("goods_photo_url not between", value1, value2, "goodsPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsStartTimeIsNull() {
            addCriterion("goods_start_time is null");
            return (Criteria) this;
        }

        public Criteria andGoodsStartTimeIsNotNull() {
            addCriterion("goods_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsStartTimeEqualTo(Date value) {
            addCriterion("goods_start_time =", value, "goodsStartTime");
            return (Criteria) this;
        }

        public Criteria andGoodsStartTimeNotEqualTo(Date value) {
            addCriterion("goods_start_time <>", value, "goodsStartTime");
            return (Criteria) this;
        }

        public Criteria andGoodsStartTimeGreaterThan(Date value) {
            addCriterion("goods_start_time >", value, "goodsStartTime");
            return (Criteria) this;
        }

        public Criteria andGoodsStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("goods_start_time >=", value, "goodsStartTime");
            return (Criteria) this;
        }

        public Criteria andGoodsStartTimeLessThan(Date value) {
            addCriterion("goods_start_time <", value, "goodsStartTime");
            return (Criteria) this;
        }

        public Criteria andGoodsStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("goods_start_time <=", value, "goodsStartTime");
            return (Criteria) this;
        }

        public Criteria andGoodsStartTimeIn(List<Date> values) {
            addCriterion("goods_start_time in", values, "goodsStartTime");
            return (Criteria) this;
        }

        public Criteria andGoodsStartTimeNotIn(List<Date> values) {
            addCriterion("goods_start_time not in", values, "goodsStartTime");
            return (Criteria) this;
        }

        public Criteria andGoodsStartTimeBetween(Date value1, Date value2) {
            addCriterion("goods_start_time between", value1, value2, "goodsStartTime");
            return (Criteria) this;
        }

        public Criteria andGoodsStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("goods_start_time not between", value1, value2, "goodsStartTime");
            return (Criteria) this;
        }

        public Criteria andGoodsEndTimeIsNull() {
            addCriterion("goods_end_time is null");
            return (Criteria) this;
        }

        public Criteria andGoodsEndTimeIsNotNull() {
            addCriterion("goods_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsEndTimeEqualTo(Date value) {
            addCriterion("goods_end_time =", value, "goodsEndTime");
            return (Criteria) this;
        }

        public Criteria andGoodsEndTimeNotEqualTo(Date value) {
            addCriterion("goods_end_time <>", value, "goodsEndTime");
            return (Criteria) this;
        }

        public Criteria andGoodsEndTimeGreaterThan(Date value) {
            addCriterion("goods_end_time >", value, "goodsEndTime");
            return (Criteria) this;
        }

        public Criteria andGoodsEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("goods_end_time >=", value, "goodsEndTime");
            return (Criteria) this;
        }

        public Criteria andGoodsEndTimeLessThan(Date value) {
            addCriterion("goods_end_time <", value, "goodsEndTime");
            return (Criteria) this;
        }

        public Criteria andGoodsEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("goods_end_time <=", value, "goodsEndTime");
            return (Criteria) this;
        }

        public Criteria andGoodsEndTimeIn(List<Date> values) {
            addCriterion("goods_end_time in", values, "goodsEndTime");
            return (Criteria) this;
        }

        public Criteria andGoodsEndTimeNotIn(List<Date> values) {
            addCriterion("goods_end_time not in", values, "goodsEndTime");
            return (Criteria) this;
        }

        public Criteria andGoodsEndTimeBetween(Date value1, Date value2) {
            addCriterion("goods_end_time between", value1, value2, "goodsEndTime");
            return (Criteria) this;
        }

        public Criteria andGoodsEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("goods_end_time not between", value1, value2, "goodsEndTime");
            return (Criteria) this;
        }

        public Criteria andGoodsIntroduceIsNull() {
            addCriterion("goods_introduce is null");
            return (Criteria) this;
        }

        public Criteria andGoodsIntroduceIsNotNull() {
            addCriterion("goods_introduce is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsIntroduceEqualTo(String value) {
            addCriterion("goods_introduce =", value, "goodsIntroduce");
            return (Criteria) this;
        }

        public Criteria andGoodsIntroduceNotEqualTo(String value) {
            addCriterion("goods_introduce <>", value, "goodsIntroduce");
            return (Criteria) this;
        }

        public Criteria andGoodsIntroduceGreaterThan(String value) {
            addCriterion("goods_introduce >", value, "goodsIntroduce");
            return (Criteria) this;
        }

        public Criteria andGoodsIntroduceGreaterThanOrEqualTo(String value) {
            addCriterion("goods_introduce >=", value, "goodsIntroduce");
            return (Criteria) this;
        }

        public Criteria andGoodsIntroduceLessThan(String value) {
            addCriterion("goods_introduce <", value, "goodsIntroduce");
            return (Criteria) this;
        }

        public Criteria andGoodsIntroduceLessThanOrEqualTo(String value) {
            addCriterion("goods_introduce <=", value, "goodsIntroduce");
            return (Criteria) this;
        }

        public Criteria andGoodsIntroduceLike(String value) {
            addCriterion("goods_introduce like", value, "goodsIntroduce");
            return (Criteria) this;
        }

        public Criteria andGoodsIntroduceNotLike(String value) {
            addCriterion("goods_introduce not like", value, "goodsIntroduce");
            return (Criteria) this;
        }

        public Criteria andGoodsIntroduceIn(List<String> values) {
            addCriterion("goods_introduce in", values, "goodsIntroduce");
            return (Criteria) this;
        }

        public Criteria andGoodsIntroduceNotIn(List<String> values) {
            addCriterion("goods_introduce not in", values, "goodsIntroduce");
            return (Criteria) this;
        }

        public Criteria andGoodsIntroduceBetween(String value1, String value2) {
            addCriterion("goods_introduce between", value1, value2, "goodsIntroduce");
            return (Criteria) this;
        }

        public Criteria andGoodsIntroduceNotBetween(String value1, String value2) {
            addCriterion("goods_introduce not between", value1, value2, "goodsIntroduce");
            return (Criteria) this;
        }

        public Criteria andGoodsFlagIsNull() {
            addCriterion("goods_flag is null");
            return (Criteria) this;
        }

        public Criteria andGoodsFlagIsNotNull() {
            addCriterion("goods_flag is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsFlagEqualTo(Integer value) {
            addCriterion("goods_flag =", value, "goodsFlag");
            return (Criteria) this;
        }

        public Criteria andGoodsFlagNotEqualTo(Integer value) {
            addCriterion("goods_flag <>", value, "goodsFlag");
            return (Criteria) this;
        }

        public Criteria andGoodsFlagGreaterThan(Integer value) {
            addCriterion("goods_flag >", value, "goodsFlag");
            return (Criteria) this;
        }

        public Criteria andGoodsFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("goods_flag >=", value, "goodsFlag");
            return (Criteria) this;
        }

        public Criteria andGoodsFlagLessThan(Integer value) {
            addCriterion("goods_flag <", value, "goodsFlag");
            return (Criteria) this;
        }

        public Criteria andGoodsFlagLessThanOrEqualTo(Integer value) {
            addCriterion("goods_flag <=", value, "goodsFlag");
            return (Criteria) this;
        }

        public Criteria andGoodsFlagIn(List<Integer> values) {
            addCriterion("goods_flag in", values, "goodsFlag");
            return (Criteria) this;
        }

        public Criteria andGoodsFlagNotIn(List<Integer> values) {
            addCriterion("goods_flag not in", values, "goodsFlag");
            return (Criteria) this;
        }

        public Criteria andGoodsFlagBetween(Integer value1, Integer value2) {
            addCriterion("goods_flag between", value1, value2, "goodsFlag");
            return (Criteria) this;
        }

        public Criteria andGoodsFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("goods_flag not between", value1, value2, "goodsFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_goods
     *
     * @mbg.generated do_not_delete_during_merge Mon Feb 01 12:56:39 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_goods
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}