package com.hoperun.pesystem.model;

import java.io.Serializable;

public class Praise implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_praise.praise_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Integer praiseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_praise.praise_type_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Integer praiseTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_praise.praise_user_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Integer praiseUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_praise.praise_id
     *
     * @return the value of t_praise.praise_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Integer getPraiseId() {
        return praiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_praise.praise_id
     *
     * @param praiseId the value for t_praise.praise_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setPraiseId(Integer praiseId) {
        this.praiseId = praiseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_praise.praise_type_id
     *
     * @return the value of t_praise.praise_type_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Integer getPraiseTypeId() {
        return praiseTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_praise.praise_type_id
     *
     * @param praiseTypeId the value for t_praise.praise_type_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setPraiseTypeId(Integer praiseTypeId) {
        this.praiseTypeId = praiseTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_praise.praise_user_id
     *
     * @return the value of t_praise.praise_user_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Integer getPraiseUserId() {
        return praiseUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_praise.praise_user_id
     *
     * @param praiseUserId the value for t_praise.praise_user_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setPraiseUserId(Integer praiseUserId) {
        this.praiseUserId = praiseUserId;
    }
}