package com.hoperun.pesystem.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StudyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public StudyExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStuIdIsNull() {
            addCriterion("stu_id is null");
            return (Criteria) this;
        }

        public Criteria andStuIdIsNotNull() {
            addCriterion("stu_id is not null");
            return (Criteria) this;
        }

        public Criteria andStuIdEqualTo(Integer value) {
            addCriterion("stu_id =", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdNotEqualTo(Integer value) {
            addCriterion("stu_id <>", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdGreaterThan(Integer value) {
            addCriterion("stu_id >", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("stu_id >=", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdLessThan(Integer value) {
            addCriterion("stu_id <", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdLessThanOrEqualTo(Integer value) {
            addCriterion("stu_id <=", value, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdIn(List<Integer> values) {
            addCriterion("stu_id in", values, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdNotIn(List<Integer> values) {
            addCriterion("stu_id not in", values, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdBetween(Integer value1, Integer value2) {
            addCriterion("stu_id between", value1, value2, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("stu_id not between", value1, value2, "stuId");
            return (Criteria) this;
        }

        public Criteria andStuTitleIsNull() {
            addCriterion("stu_title is null");
            return (Criteria) this;
        }

        public Criteria andStuTitleIsNotNull() {
            addCriterion("stu_title is not null");
            return (Criteria) this;
        }

        public Criteria andStuTitleEqualTo(String value) {
            addCriterion("stu_title =", value, "stuTitle");
            return (Criteria) this;
        }

        public Criteria andStuTitleNotEqualTo(String value) {
            addCriterion("stu_title <>", value, "stuTitle");
            return (Criteria) this;
        }

        public Criteria andStuTitleGreaterThan(String value) {
            addCriterion("stu_title >", value, "stuTitle");
            return (Criteria) this;
        }

        public Criteria andStuTitleGreaterThanOrEqualTo(String value) {
            addCriterion("stu_title >=", value, "stuTitle");
            return (Criteria) this;
        }

        public Criteria andStuTitleLessThan(String value) {
            addCriterion("stu_title <", value, "stuTitle");
            return (Criteria) this;
        }

        public Criteria andStuTitleLessThanOrEqualTo(String value) {
            addCriterion("stu_title <=", value, "stuTitle");
            return (Criteria) this;
        }

        public Criteria andStuTitleLike(String value) {
            addCriterion("stu_title like", value, "stuTitle");
            return (Criteria) this;
        }

        public Criteria andStuTitleNotLike(String value) {
            addCriterion("stu_title not like", value, "stuTitle");
            return (Criteria) this;
        }

        public Criteria andStuTitleIn(List<String> values) {
            addCriterion("stu_title in", values, "stuTitle");
            return (Criteria) this;
        }

        public Criteria andStuTitleNotIn(List<String> values) {
            addCriterion("stu_title not in", values, "stuTitle");
            return (Criteria) this;
        }

        public Criteria andStuTitleBetween(String value1, String value2) {
            addCriterion("stu_title between", value1, value2, "stuTitle");
            return (Criteria) this;
        }

        public Criteria andStuTitleNotBetween(String value1, String value2) {
            addCriterion("stu_title not between", value1, value2, "stuTitle");
            return (Criteria) this;
        }

        public Criteria andStuIntroduceIsNull() {
            addCriterion("stu_introduce is null");
            return (Criteria) this;
        }

        public Criteria andStuIntroduceIsNotNull() {
            addCriterion("stu_introduce is not null");
            return (Criteria) this;
        }

        public Criteria andStuIntroduceEqualTo(String value) {
            addCriterion("stu_introduce =", value, "stuIntroduce");
            return (Criteria) this;
        }

        public Criteria andStuIntroduceNotEqualTo(String value) {
            addCriterion("stu_introduce <>", value, "stuIntroduce");
            return (Criteria) this;
        }

        public Criteria andStuIntroduceGreaterThan(String value) {
            addCriterion("stu_introduce >", value, "stuIntroduce");
            return (Criteria) this;
        }

        public Criteria andStuIntroduceGreaterThanOrEqualTo(String value) {
            addCriterion("stu_introduce >=", value, "stuIntroduce");
            return (Criteria) this;
        }

        public Criteria andStuIntroduceLessThan(String value) {
            addCriterion("stu_introduce <", value, "stuIntroduce");
            return (Criteria) this;
        }

        public Criteria andStuIntroduceLessThanOrEqualTo(String value) {
            addCriterion("stu_introduce <=", value, "stuIntroduce");
            return (Criteria) this;
        }

        public Criteria andStuIntroduceLike(String value) {
            addCriterion("stu_introduce like", value, "stuIntroduce");
            return (Criteria) this;
        }

        public Criteria andStuIntroduceNotLike(String value) {
            addCriterion("stu_introduce not like", value, "stuIntroduce");
            return (Criteria) this;
        }

        public Criteria andStuIntroduceIn(List<String> values) {
            addCriterion("stu_introduce in", values, "stuIntroduce");
            return (Criteria) this;
        }

        public Criteria andStuIntroduceNotIn(List<String> values) {
            addCriterion("stu_introduce not in", values, "stuIntroduce");
            return (Criteria) this;
        }

        public Criteria andStuIntroduceBetween(String value1, String value2) {
            addCriterion("stu_introduce between", value1, value2, "stuIntroduce");
            return (Criteria) this;
        }

        public Criteria andStuIntroduceNotBetween(String value1, String value2) {
            addCriterion("stu_introduce not between", value1, value2, "stuIntroduce");
            return (Criteria) this;
        }

        public Criteria andStuTypeIdIsNull() {
            addCriterion("stu_type_id is null");
            return (Criteria) this;
        }

        public Criteria andStuTypeIdIsNotNull() {
            addCriterion("stu_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andStuTypeIdEqualTo(Integer value) {
            addCriterion("stu_type_id =", value, "stuTypeId");
            return (Criteria) this;
        }

        public Criteria andStuTypeIdNotEqualTo(Integer value) {
            addCriterion("stu_type_id <>", value, "stuTypeId");
            return (Criteria) this;
        }

        public Criteria andStuTypeIdGreaterThan(Integer value) {
            addCriterion("stu_type_id >", value, "stuTypeId");
            return (Criteria) this;
        }

        public Criteria andStuTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("stu_type_id >=", value, "stuTypeId");
            return (Criteria) this;
        }

        public Criteria andStuTypeIdLessThan(Integer value) {
            addCriterion("stu_type_id <", value, "stuTypeId");
            return (Criteria) this;
        }

        public Criteria andStuTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("stu_type_id <=", value, "stuTypeId");
            return (Criteria) this;
        }

        public Criteria andStuTypeIdIn(List<Integer> values) {
            addCriterion("stu_type_id in", values, "stuTypeId");
            return (Criteria) this;
        }

        public Criteria andStuTypeIdNotIn(List<Integer> values) {
            addCriterion("stu_type_id not in", values, "stuTypeId");
            return (Criteria) this;
        }

        public Criteria andStuTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("stu_type_id between", value1, value2, "stuTypeId");
            return (Criteria) this;
        }

        public Criteria andStuTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("stu_type_id not between", value1, value2, "stuTypeId");
            return (Criteria) this;
        }

        public Criteria andStuBrowseNumberIsNull() {
            addCriterion("stu_browse_number is null");
            return (Criteria) this;
        }

        public Criteria andStuBrowseNumberIsNotNull() {
            addCriterion("stu_browse_number is not null");
            return (Criteria) this;
        }

        public Criteria andStuBrowseNumberEqualTo(Integer value) {
            addCriterion("stu_browse_number =", value, "stuBrowseNumber");
            return (Criteria) this;
        }

        public Criteria andStuBrowseNumberNotEqualTo(Integer value) {
            addCriterion("stu_browse_number <>", value, "stuBrowseNumber");
            return (Criteria) this;
        }

        public Criteria andStuBrowseNumberGreaterThan(Integer value) {
            addCriterion("stu_browse_number >", value, "stuBrowseNumber");
            return (Criteria) this;
        }

        public Criteria andStuBrowseNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("stu_browse_number >=", value, "stuBrowseNumber");
            return (Criteria) this;
        }

        public Criteria andStuBrowseNumberLessThan(Integer value) {
            addCriterion("stu_browse_number <", value, "stuBrowseNumber");
            return (Criteria) this;
        }

        public Criteria andStuBrowseNumberLessThanOrEqualTo(Integer value) {
            addCriterion("stu_browse_number <=", value, "stuBrowseNumber");
            return (Criteria) this;
        }

        public Criteria andStuBrowseNumberIn(List<Integer> values) {
            addCriterion("stu_browse_number in", values, "stuBrowseNumber");
            return (Criteria) this;
        }

        public Criteria andStuBrowseNumberNotIn(List<Integer> values) {
            addCriterion("stu_browse_number not in", values, "stuBrowseNumber");
            return (Criteria) this;
        }

        public Criteria andStuBrowseNumberBetween(Integer value1, Integer value2) {
            addCriterion("stu_browse_number between", value1, value2, "stuBrowseNumber");
            return (Criteria) this;
        }

        public Criteria andStuBrowseNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("stu_browse_number not between", value1, value2, "stuBrowseNumber");
            return (Criteria) this;
        }

        public Criteria andStuPraiseNumberIsNull() {
            addCriterion("stu_praise_number is null");
            return (Criteria) this;
        }

        public Criteria andStuPraiseNumberIsNotNull() {
            addCriterion("stu_praise_number is not null");
            return (Criteria) this;
        }

        public Criteria andStuPraiseNumberEqualTo(Integer value) {
            addCriterion("stu_praise_number =", value, "stuPraiseNumber");
            return (Criteria) this;
        }

        public Criteria andStuPraiseNumberNotEqualTo(Integer value) {
            addCriterion("stu_praise_number <>", value, "stuPraiseNumber");
            return (Criteria) this;
        }

        public Criteria andStuPraiseNumberGreaterThan(Integer value) {
            addCriterion("stu_praise_number >", value, "stuPraiseNumber");
            return (Criteria) this;
        }

        public Criteria andStuPraiseNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("stu_praise_number >=", value, "stuPraiseNumber");
            return (Criteria) this;
        }

        public Criteria andStuPraiseNumberLessThan(Integer value) {
            addCriterion("stu_praise_number <", value, "stuPraiseNumber");
            return (Criteria) this;
        }

        public Criteria andStuPraiseNumberLessThanOrEqualTo(Integer value) {
            addCriterion("stu_praise_number <=", value, "stuPraiseNumber");
            return (Criteria) this;
        }

        public Criteria andStuPraiseNumberIn(List<Integer> values) {
            addCriterion("stu_praise_number in", values, "stuPraiseNumber");
            return (Criteria) this;
        }

        public Criteria andStuPraiseNumberNotIn(List<Integer> values) {
            addCriterion("stu_praise_number not in", values, "stuPraiseNumber");
            return (Criteria) this;
        }

        public Criteria andStuPraiseNumberBetween(Integer value1, Integer value2) {
            addCriterion("stu_praise_number between", value1, value2, "stuPraiseNumber");
            return (Criteria) this;
        }

        public Criteria andStuPraiseNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("stu_praise_number not between", value1, value2, "stuPraiseNumber");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexBigUrlIsNull() {
            addCriterion("stu_photo_index_big__url is null");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexBigUrlIsNotNull() {
            addCriterion("stu_photo_index_big__url is not null");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexBigUrlEqualTo(String value) {
            addCriterion("stu_photo_index_big__url =", value, "stuPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexBigUrlNotEqualTo(String value) {
            addCriterion("stu_photo_index_big__url <>", value, "stuPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexBigUrlGreaterThan(String value) {
            addCriterion("stu_photo_index_big__url >", value, "stuPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexBigUrlGreaterThanOrEqualTo(String value) {
            addCriterion("stu_photo_index_big__url >=", value, "stuPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexBigUrlLessThan(String value) {
            addCriterion("stu_photo_index_big__url <", value, "stuPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexBigUrlLessThanOrEqualTo(String value) {
            addCriterion("stu_photo_index_big__url <=", value, "stuPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexBigUrlLike(String value) {
            addCriterion("stu_photo_index_big__url like", value, "stuPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexBigUrlNotLike(String value) {
            addCriterion("stu_photo_index_big__url not like", value, "stuPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexBigUrlIn(List<String> values) {
            addCriterion("stu_photo_index_big__url in", values, "stuPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexBigUrlNotIn(List<String> values) {
            addCriterion("stu_photo_index_big__url not in", values, "stuPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexBigUrlBetween(String value1, String value2) {
            addCriterion("stu_photo_index_big__url between", value1, value2, "stuPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexBigUrlNotBetween(String value1, String value2) {
            addCriterion("stu_photo_index_big__url not between", value1, value2, "stuPhotoIndexBigUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexSmUrlIsNull() {
            addCriterion("stu_photo_index_sm_url is null");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexSmUrlIsNotNull() {
            addCriterion("stu_photo_index_sm_url is not null");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexSmUrlEqualTo(String value) {
            addCriterion("stu_photo_index_sm_url =", value, "stuPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexSmUrlNotEqualTo(String value) {
            addCriterion("stu_photo_index_sm_url <>", value, "stuPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexSmUrlGreaterThan(String value) {
            addCriterion("stu_photo_index_sm_url >", value, "stuPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexSmUrlGreaterThanOrEqualTo(String value) {
            addCriterion("stu_photo_index_sm_url >=", value, "stuPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexSmUrlLessThan(String value) {
            addCriterion("stu_photo_index_sm_url <", value, "stuPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexSmUrlLessThanOrEqualTo(String value) {
            addCriterion("stu_photo_index_sm_url <=", value, "stuPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexSmUrlLike(String value) {
            addCriterion("stu_photo_index_sm_url like", value, "stuPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexSmUrlNotLike(String value) {
            addCriterion("stu_photo_index_sm_url not like", value, "stuPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexSmUrlIn(List<String> values) {
            addCriterion("stu_photo_index_sm_url in", values, "stuPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexSmUrlNotIn(List<String> values) {
            addCriterion("stu_photo_index_sm_url not in", values, "stuPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexSmUrlBetween(String value1, String value2) {
            addCriterion("stu_photo_index_sm_url between", value1, value2, "stuPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoIndexSmUrlNotBetween(String value1, String value2) {
            addCriterion("stu_photo_index_sm_url not between", value1, value2, "stuPhotoIndexSmUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoUrlIsNull() {
            addCriterion("stu_photo_url is null");
            return (Criteria) this;
        }

        public Criteria andStuPhotoUrlIsNotNull() {
            addCriterion("stu_photo_url is not null");
            return (Criteria) this;
        }

        public Criteria andStuPhotoUrlEqualTo(String value) {
            addCriterion("stu_photo_url =", value, "stuPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoUrlNotEqualTo(String value) {
            addCriterion("stu_photo_url <>", value, "stuPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoUrlGreaterThan(String value) {
            addCriterion("stu_photo_url >", value, "stuPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoUrlGreaterThanOrEqualTo(String value) {
            addCriterion("stu_photo_url >=", value, "stuPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoUrlLessThan(String value) {
            addCriterion("stu_photo_url <", value, "stuPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoUrlLessThanOrEqualTo(String value) {
            addCriterion("stu_photo_url <=", value, "stuPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoUrlLike(String value) {
            addCriterion("stu_photo_url like", value, "stuPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoUrlNotLike(String value) {
            addCriterion("stu_photo_url not like", value, "stuPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoUrlIn(List<String> values) {
            addCriterion("stu_photo_url in", values, "stuPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoUrlNotIn(List<String> values) {
            addCriterion("stu_photo_url not in", values, "stuPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoUrlBetween(String value1, String value2) {
            addCriterion("stu_photo_url between", value1, value2, "stuPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andStuPhotoUrlNotBetween(String value1, String value2) {
            addCriterion("stu_photo_url not between", value1, value2, "stuPhotoUrl");
            return (Criteria) this;
        }

        public Criteria andStuStartTimeIsNull() {
            addCriterion("stu_start_time is null");
            return (Criteria) this;
        }

        public Criteria andStuStartTimeIsNotNull() {
            addCriterion("stu_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStuStartTimeEqualTo(Date value) {
            addCriterion("stu_start_time =", value, "stuStartTime");
            return (Criteria) this;
        }

        public Criteria andStuStartTimeNotEqualTo(Date value) {
            addCriterion("stu_start_time <>", value, "stuStartTime");
            return (Criteria) this;
        }

        public Criteria andStuStartTimeGreaterThan(Date value) {
            addCriterion("stu_start_time >", value, "stuStartTime");
            return (Criteria) this;
        }

        public Criteria andStuStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("stu_start_time >=", value, "stuStartTime");
            return (Criteria) this;
        }

        public Criteria andStuStartTimeLessThan(Date value) {
            addCriterion("stu_start_time <", value, "stuStartTime");
            return (Criteria) this;
        }

        public Criteria andStuStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("stu_start_time <=", value, "stuStartTime");
            return (Criteria) this;
        }

        public Criteria andStuStartTimeIn(List<Date> values) {
            addCriterion("stu_start_time in", values, "stuStartTime");
            return (Criteria) this;
        }

        public Criteria andStuStartTimeNotIn(List<Date> values) {
            addCriterion("stu_start_time not in", values, "stuStartTime");
            return (Criteria) this;
        }

        public Criteria andStuStartTimeBetween(Date value1, Date value2) {
            addCriterion("stu_start_time between", value1, value2, "stuStartTime");
            return (Criteria) this;
        }

        public Criteria andStuStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("stu_start_time not between", value1, value2, "stuStartTime");
            return (Criteria) this;
        }

        public Criteria andStuEndTimeIsNull() {
            addCriterion("stu_end_time is null");
            return (Criteria) this;
        }

        public Criteria andStuEndTimeIsNotNull() {
            addCriterion("stu_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andStuEndTimeEqualTo(Date value) {
            addCriterion("stu_end_time =", value, "stuEndTime");
            return (Criteria) this;
        }

        public Criteria andStuEndTimeNotEqualTo(Date value) {
            addCriterion("stu_end_time <>", value, "stuEndTime");
            return (Criteria) this;
        }

        public Criteria andStuEndTimeGreaterThan(Date value) {
            addCriterion("stu_end_time >", value, "stuEndTime");
            return (Criteria) this;
        }

        public Criteria andStuEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("stu_end_time >=", value, "stuEndTime");
            return (Criteria) this;
        }

        public Criteria andStuEndTimeLessThan(Date value) {
            addCriterion("stu_end_time <", value, "stuEndTime");
            return (Criteria) this;
        }

        public Criteria andStuEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("stu_end_time <=", value, "stuEndTime");
            return (Criteria) this;
        }

        public Criteria andStuEndTimeIn(List<Date> values) {
            addCriterion("stu_end_time in", values, "stuEndTime");
            return (Criteria) this;
        }

        public Criteria andStuEndTimeNotIn(List<Date> values) {
            addCriterion("stu_end_time not in", values, "stuEndTime");
            return (Criteria) this;
        }

        public Criteria andStuEndTimeBetween(Date value1, Date value2) {
            addCriterion("stu_end_time between", value1, value2, "stuEndTime");
            return (Criteria) this;
        }

        public Criteria andStuEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("stu_end_time not between", value1, value2, "stuEndTime");
            return (Criteria) this;
        }

        public Criteria andStuFlagIsNull() {
            addCriterion("stu_flag is null");
            return (Criteria) this;
        }

        public Criteria andStuFlagIsNotNull() {
            addCriterion("stu_flag is not null");
            return (Criteria) this;
        }

        public Criteria andStuFlagEqualTo(Integer value) {
            addCriterion("stu_flag =", value, "stuFlag");
            return (Criteria) this;
        }

        public Criteria andStuFlagNotEqualTo(Integer value) {
            addCriterion("stu_flag <>", value, "stuFlag");
            return (Criteria) this;
        }

        public Criteria andStuFlagGreaterThan(Integer value) {
            addCriterion("stu_flag >", value, "stuFlag");
            return (Criteria) this;
        }

        public Criteria andStuFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("stu_flag >=", value, "stuFlag");
            return (Criteria) this;
        }

        public Criteria andStuFlagLessThan(Integer value) {
            addCriterion("stu_flag <", value, "stuFlag");
            return (Criteria) this;
        }

        public Criteria andStuFlagLessThanOrEqualTo(Integer value) {
            addCriterion("stu_flag <=", value, "stuFlag");
            return (Criteria) this;
        }

        public Criteria andStuFlagIn(List<Integer> values) {
            addCriterion("stu_flag in", values, "stuFlag");
            return (Criteria) this;
        }

        public Criteria andStuFlagNotIn(List<Integer> values) {
            addCriterion("stu_flag not in", values, "stuFlag");
            return (Criteria) this;
        }

        public Criteria andStuFlagBetween(Integer value1, Integer value2) {
            addCriterion("stu_flag between", value1, value2, "stuFlag");
            return (Criteria) this;
        }

        public Criteria andStuFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("stu_flag not between", value1, value2, "stuFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_study
     *
     * @mbg.generated do_not_delete_during_merge Mon Feb 01 12:56:39 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}