package com.hoperun.pesystem.model;

import java.io.Serializable;

public class Type implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_type.type_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_type.type_flag
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Integer typeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_type.type_name
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private String typeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_type.type_id
     *
     * @return the value of t_type.type_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_type.type_id
     *
     * @param typeId the value for t_type.type_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_type.type_flag
     *
     * @return the value of t_type.type_flag
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Integer getTypeFlag() {
        return typeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_type.type_flag
     *
     * @param typeFlag the value for t_type.type_flag
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setTypeFlag(Integer typeFlag) {
        this.typeFlag = typeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_type.type_name
     *
     * @return the value of t_type.type_name
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_type.type_name
     *
     * @param typeName the value for t_type.type_name
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }
}