package com.hoperun.pesystem.model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_username
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private String userUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_password
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_phone_number
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private String userPhoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_caption_url
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private String userCaptionUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_birthday
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Date userBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_integral
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    private Integer userIntegral;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_id
     *
     * @return the value of t_user.user_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_id
     *
     * @param userId the value for t_user.user_id
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_username
     *
     * @return the value of t_user.user_username
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getUserUsername() {
        return userUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_username
     *
     * @param userUsername the value for t_user.user_username
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setUserUsername(String userUsername) {
        this.userUsername = userUsername == null ? null : userUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_password
     *
     * @return the value of t_user.user_password
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_password
     *
     * @param userPassword the value for t_user.user_password
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_phone_number
     *
     * @return the value of t_user.user_phone_number
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getUserPhoneNumber() {
        return userPhoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_phone_number
     *
     * @param userPhoneNumber the value for t_user.user_phone_number
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setUserPhoneNumber(String userPhoneNumber) {
        this.userPhoneNumber = userPhoneNumber == null ? null : userPhoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_caption_url
     *
     * @return the value of t_user.user_caption_url
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public String getUserCaptionUrl() {
        return userCaptionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_caption_url
     *
     * @param userCaptionUrl the value for t_user.user_caption_url
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setUserCaptionUrl(String userCaptionUrl) {
        this.userCaptionUrl = userCaptionUrl == null ? null : userCaptionUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_birthday
     *
     * @return the value of t_user.user_birthday
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Date getUserBirthday() {
        return userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_birthday
     *
     * @param userBirthday the value for t_user.user_birthday
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_integral
     *
     * @return the value of t_user.user_integral
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public Integer getUserIntegral() {
        return userIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_integral
     *
     * @param userIntegral the value for t_user.user_integral
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    public void setUserIntegral(Integer userIntegral) {
        this.userIntegral = userIntegral;
    }
}