package com.hoperun.pesystem.mapper;

import com.hoperun.pesystem.model.Browse;
import com.hoperun.pesystem.model.BrowseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface BrowseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    long countByExample(BrowseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int deleteByExample(BrowseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int deleteByPrimaryKey(Integer browseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int insert(Browse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int insertSelective(Browse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    List<Browse> selectByExampleWithRowbounds(BrowseExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    List<Browse> selectByExample(BrowseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    Browse selectByPrimaryKey(Integer browseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int updateByExampleSelective(@Param("record") Browse record, @Param("example") BrowseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int updateByExample(@Param("record") Browse record, @Param("example") BrowseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int updateByPrimaryKeySelective(Browse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int updateByPrimaryKey(Browse record);
}