package com.hoperun.pesystem.mapper;

import com.hoperun.pesystem.model.Exchange;
import com.hoperun.pesystem.model.ExchangeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface ExchangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    long countByExample(ExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int deleteByExample(ExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int deleteByPrimaryKey(Integer exId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int insert(Exchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int insertSelective(Exchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    List<Exchange> selectByExampleWithRowbounds(ExchangeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    List<Exchange> selectByExample(ExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    Exchange selectByPrimaryKey(Integer exId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int updateByExampleSelective(@Param("record") Exchange record, @Param("example") ExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int updateByExample(@Param("record") Exchange record, @Param("example") ExchangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int updateByPrimaryKeySelective(Exchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exchange
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int updateByPrimaryKey(Exchange record);
}