package com.hoperun.pesystem.mapper;

import com.hoperun.pesystem.model.Praise;
import com.hoperun.pesystem.model.PraiseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface PraiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_praise
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    long countByExample(PraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_praise
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int deleteByExample(PraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_praise
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int deleteByPrimaryKey(Integer praiseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_praise
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int insert(Praise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_praise
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int insertSelective(Praise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_praise
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    List<Praise> selectByExampleWithRowbounds(PraiseExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_praise
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    List<Praise> selectByExample(PraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_praise
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    Praise selectByPrimaryKey(Integer praiseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_praise
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int updateByExampleSelective(@Param("record") Praise record, @Param("example") PraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_praise
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int updateByExample(@Param("record") Praise record, @Param("example") PraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_praise
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int updateByPrimaryKeySelective(Praise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_praise
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int updateByPrimaryKey(Praise record);
}