package com.hoperun.pesystem.mapper;

import com.hoperun.pesystem.model.Study;
import com.hoperun.pesystem.model.StudyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface StudyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    long countByExample(StudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int deleteByExample(StudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int deleteByPrimaryKey(Integer stuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int insert(Study record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int insertSelective(Study record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    List<Study> selectByExampleWithBLOBsWithRowbounds(StudyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    List<Study> selectByExampleWithBLOBs(StudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    List<Study> selectByExampleWithRowbounds(StudyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    List<Study> selectByExample(StudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    Study selectByPrimaryKey(Integer stuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int updateByExampleSelective(@Param("record") Study record, @Param("example") StudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") Study record, @Param("example") StudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int updateByExample(@Param("record") Study record, @Param("example") StudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int updateByPrimaryKeySelective(Study record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(Study record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_study
     *
     * @mbg.generated Mon Feb 01 12:56:39 CST 2021
     */
    int updateByPrimaryKey(Study record);
}